### ISSUE TITLE
  Class "BagServiceProvider" not found

### ISSUE THREAD

**Issue by JoeCianflone** [dshafik/bag#20]
**Describe the bug**
Attempting to install Bag via the CLI leards to `In ProviderRepository.php line 206: Class "BagServiceProvider" not found` 

**To Reproduce**

```php
composer require dshafik/bag
```

**Expected behavior**

**System (please complete the following information):**
 - OS: macOS
 - PHP Version: 8.2
 - Bag Version: dev? 

**Additional context**
Laravel 11.0.6, brand new install, I do need to change stability in composer to to "dev" order to get this far

**Comment by dshafik** [comment]
@JoeCianflone this issue was resolved a couple of days ago, see https://github.com/dshafik/bag/commit/0c55b5433a073845fa72a6581d868982fb255f27

Are you still seeing this with the latest `dev-main` "version"?

**Comment by JoeCianflone** [comment]
@dshafik I just did a standard `composer require` and it was pulling in `*` (which I think should just be `dev-main`) but I just deleted everything and ran it again and it seems to work now

**Comment by JoeCianflone** [comment]
I'm going to close this, if I hit this again I'll dig more into it and see what, if anything, is going on, but it seems good now!
